openapi: 3.0.0

info:
  title: API document for Banking Ledger System
  version: 1.0.0
    
servers:
  - url: http://localhost:{port}

paths:
  /accounts/{id}:        
    get:
      tags:
        - "Accounts"
      summary: View current balance for Customer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true      
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountReadModel"
                
  /accounts/create:        
    post:
      tags:
        - "Accounts"
      summary: Create account for customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountCreateBody"      
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountReadModel"              

  /accounts/create-admin:        
    post:
      tags:
        - "Accounts"
      summary: Create account for customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountCreateBody"      
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountReadModel"           
                
components:
  schemas:
    AccountReadModel:
      type: object
      properties:
        id:
          type: string
        name:
          type: string               
        balance:
          type: integer       
    AccountCreateBody:
      type: object
      properties:
        name:
          type: string               
        password:
          type: string      
          